//$c1	JT  12/19/00 Created
//========================================================================//
//
//     File Name: amapp.h
//     
//     Application: typelib
//     
//     Contents: Wrapper for the IDL generated header file.
//				 The .c/.h files generated by MIDL of MainWin are 
//               not compatible with the ones generated on NT.
//               [Mainsoft TID: 0200-0010]
//
//========================================================================//

#ifdef MAINWIN
#  include "unix/amapp.h"
#else
#  include "win32/amapp.h"
#endif
