//$c1   PXK/ASK 05/06/03 Convert swconst.h into a typelib. 
//========================================================================//
//              Copyright 2003 (Unpublished Material)                     //
//                  SolidWorks Corp.									  //
//========================================================================//
//
//     File Name: swconst_i.h
//     
//     Application: typelib
//     
//     Contents: Wrapper for the IDL generated header file.
//				 The .c/.h files generated by MIDL of MainWin are 
//               not compatible with the ones generated on NT.
//               [Mainsoft TID: 0200-0010]
//
//========================================================================//

#ifdef MAINWIN
#  include "unix/swconst.h"
#else
#  include "win32/swconst.h"
#endif

// PLEASE ADD NEW CONSTANTS TO : sldworks/utils/typelib/swconst.idl
