//$c1   JND 10/28/05 Created
//========================================================================//
//              Copyright 2003 (Unpublished Material)                     //
//                  SolidWorks Corp.									  //
//========================================================================//
//
//     File Name: swcommands_i.h
//     
//     Application: typelib
//     
//     Contents: Wrapper for the IDL generated header file.
//				 The .c/.h files generated by MIDL of MainWin are 
//               not compatible with the ones generated on NT.
//               [Mainsoft TID: 0200-0010]
//
//========================================================================//

#ifdef MAINWIN
#  include "unix/swcommands.h"
#else
#  include "win32/swcommands.h"
#endif

// PLEASE ADD NEW CONSTANTS TO : sldworks/utils/typelib/swcommands.idl
